FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Ordering.Worker/Ordering.Worker.csproj", "Ordering.Worker/"]
COPY ["Ordering.Components/Ordering.Components.csproj", "Ordering.Components/"]
RUN dotnet restore "Ordering.Worker/Ordering.Worker.csproj"

COPY . .
RUN dotnet publish -c Release -o /app Ordering.Worker/Ordering.Worker.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Ordering.Worker.dll"]
