FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# فقط csprojها را کپی کن
COPY ["Gateway/ApiGateway/ApiGateway.csproj", "Gateway/ApiGateway/"]
COPY ["BuildingBlocks/BuildingBlocks/BuildingBlocks.csproj", "BuildingBlocks/BuildingBlocks/"]

# به جای restore معمولی، از کشِ اختصاصی Nuget استفاده می‌کنیم
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore "Gateway/ApiGateway/ApiGateway.csproj"

COPY . .

# Build و Publish
RUN dotnet publish "Gateway/ApiGateway/ApiGateway.csproj" -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final

WORKDIR /app
COPY --from=build /app .
EXPOSE 80
ENTRYPOINT ["dotnet", "ApiGateway.dll"]
