FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Ordering/Ordering.Worker/Ordering.Worker.csproj", "Ordering/Ordering.Worker/"]

# به جای restore معمولی، از کشِ اختصاصی Nuget استفاده می‌کنیم
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore "Ordering/Ordering.Worker/Ordering.Worker.csproj"

COPY . .

# Build و Publish
RUN dotnet publish "Ordering/Ordering.Worker/Ordering.Worker.csproj" -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final

WORKDIR /app
COPY --from=build /app .
EXPOSE 80
ENTRYPOINT ["dotnet", "Ordering.Worker.dll"]