FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Ordering/Ordering.Api/Ordering.Api.csproj", "Ordering/Ordering.Api/"]
COPY ["Ordering/Ordering.Application/Ordering.Application.csproj", "Ordering/Ordering.Application/"]
COPY ["Ordering/Ordering.Domain/Ordering.Domain.csproj", "Ordering/Ordering.Domain/"]
COPY ["Ordering/Ordering.Infrastructure/Ordering.Infrastructure.csproj", "Ordering/Ordering.Infrastructure/"]
COPY ["BuildingBlocks/BuildingBlocks/BuildingBlocks.csproj", "BuildingBlocks/BuildingBlocks/"]
COPY ["BuildingBlocks/BuildingBlocks.Messaging/BuildingBlocks.Messaging.csproj", "BuildingBlocks/BuildingBlocks.Messaging/"]
COPY ["BuildingBlocks/Protos/OrderGrpcContracts/OrderGrpcContracts.csproj", "BuildingBlocks/Protos/OrderGrpcContracts/"]
COPY ["BuildingBlocks/Protos/ProductGrpcContracts/ProductGrpcContracts.csproj", "BuildingBlocks/Protos/ProductGrpcContracts/"]

# به جای restore معمولی، از کشِ اختصاصی Nuget استفاده می‌کنیم
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore "Ordering/Ordering.Api/Ordering.Api.csproj"

COPY . .

# Build و Publish
RUN dotnet publish "Ordering/Ordering.Api/Ordering.Api.csproj" -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final

WORKDIR /app
COPY --from=build /app .
EXPOSE 80
ENTRYPOINT ["dotnet", "Ordering.Api.dll"]